import { CreateDeviceBodySchema, CreateOtpCodeBodySchema, CreateRefreshTokenBodySchema, CreateRefreshTokenResponseSchema, DeviceSchema, GetMeResponseSchema, GoogleAuthCallbackQuerySchema, GoogleAuthCallbackResponseSchema, GoogleAuthResponseSchema, GoogleAuthStateSchema, JwtTokenSchema, LoginBodySchema, LoginResponseSchema, LogoutBodySchema, OtpCodeSchema, RefreshJwtTokenBodySchema, RefreshJwtTokenResponseSchema, RefreshTokenSchema, RegisterBodySchema, RegisterResponseSchema, RoleSchema, SendOtpBodySchema } from "@/routes/auth/models/auth.model";
import z from "zod";

export type JwtTokenType = z.infer<typeof JwtTokenSchema>;
export type GetMeResponseType = z.infer<typeof GetMeResponseSchema>;
export type DeviceType = z.infer<typeof DeviceSchema>;
export type CreateDeviceBodyType = z.infer<typeof CreateDeviceBodySchema> & Partial<Pick<DeviceType, 'isActive' | 'lastActiveAt'>>;
export type RoleType = z.infer<typeof RoleSchema>;
export type RegisterBodyType = z.infer<typeof RegisterBodySchema>;
export type RegisterResponseType = z.infer<typeof RegisterResponseSchema>;
export type LoginBodyType = z.infer<typeof LoginBodySchema>;
export type LoginResponseType = z.infer<typeof LoginResponseSchema>;
export type LogoutBodyType = z.infer<typeof LogoutBodySchema>;
export type RefreshTokenType = z.infer<typeof RefreshTokenSchema>;
export type CreateRefreshTokenBodyType = z.infer<typeof CreateRefreshTokenBodySchema>;
export type CreateRefreshTokenResponseType = z.infer<typeof CreateRefreshTokenResponseSchema>;
export type RefreshJwtTokenBodyType = z.infer<typeof RefreshJwtTokenBodySchema>;
export type RefreshJwtTokenResponseType = z.infer<typeof RefreshJwtTokenResponseSchema>;
export type OtpCodeType = z.infer<typeof OtpCodeSchema>;
export type CreateOtpCodeBodyType = z.infer<typeof CreateOtpCodeBodySchema>;
export type SendOtpBodyType = z.infer<typeof SendOtpBodySchema>;
export type GoogleAuthStateType = z.infer<typeof GoogleAuthStateSchema>;
export type GoogleAuthResponseType = z.infer<typeof GoogleAuthResponseSchema>;
export type GoogleAuthCallbackQueryType = z.infer<typeof GoogleAuthCallbackQuerySchema>;
export type GoogleAuthCallbackResponseType = z.infer<typeof GoogleAuthCallbackResponseSchema>;
